apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: nicolajh/swj-authentication
          ports:
            - containerPort: 3000
          env:
            - name: MONGOURL
              valueFrom:
                secretKeyRef:
                  name: databasesecrets
                  key: connection-string-authentication-service
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: jwtsecret
                  key: secret
          resources:
            limits:  
              cpu: "500m"
              memory: "500Mi"
            requests:  
              cpu: "500m"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
